services:
  prxdbeats:
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./app.py:/app/app.py
      - ./db.py:/app/db.py
      - ./generate_pulse.py:/app/generate_pulse.py
      - ./templates:/app/templates
      - ./assets:/app/assets